### ISSUE TITLE
Exporting webfonts fails

### ISSUE THREAD

**Issue by rbmntjs** [typemytype/batchRoboFontExtension#1]
The file exports fine with the normal generate command. The traceback is as follows:

```
******************************
Traceback (most recent call last):
  File "/var/folders/8y/vjr0hwzx58q4ntt120h4n4z00000gn/T/tmpNUkmwc/batchRoboFontExtension-master/Batch.roboFontExt/lib/tools.py", line 72, in runTask_
  File "/var/folders/8y/vjr0hwzx58q4ntt120h4n4z00000gn/T/tmpNUkmwc/batchRoboFontExtension-master/Batch.roboFontExt/lib/webFormats/__init__.py", line 331, in run
  File "/var/folders/8y/vjr0hwzx58q4ntt120h4n4z00000gn/T/tmpNUkmwc/batchRoboFontExtension-master/Batch.roboFontExt/lib/webFormats/__init__.py", line 231, in _convertPath
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/compositor/__init__.py", line 39, in __init__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 156, in __init__
TTLibError: Not a TrueType or OpenType font (not enough data)

******************************
Exception AttributeError: "'Font' object has no attribute 'source'" in <bound method Font.__del__ of <compositor.Font object at 0x15a3b5310>> ignored
```

**Comment by typemytype** [comment]
Could you send an example UFO? (Offlist)

**Comment by javburg** [comment]
I had the same issue. The fonts.css, preview.html and WebFonts Report generates but not the font files. The traceback I got was:

Exception AttributeError: "'Font' object has no attribute 'source'" in <bound method Font.__del__ of <compositor.Font object at 0x118c2cc10>> ignored

I then only tried generating the WOFF file as I thought it might be a TTF issue, and the WOFF generated. I then tried it again with the TTF selected as well and it generated everything without any issues. It didn't work on multiple UFO's but now all is working.

**Comment by typemytype** [comment]
I posted some updates earlier, that should fix it, please report if it doesnt

Thanks

**Comment by rbmntjs** [comment]
This same issue has returned. I don’t know how or why – it worked yesterday, stopped today. Restarted Robofont, re-installed the extension, but the same error keeps showing. It doesn’t export anything, but throws the `no attribute 'source'` error for WOFF.

**Comment by rbmntjs** [comment]
Sorry, this looks like upgrading OS X did it. I’m going through my homebrew to see what I can fix.

**Comment by rbmntjs** [comment]
What I’ve found is that if you get a failure to build at some point — for valid reasons, such as malformed features — then unless I restart the app, the Batch extension will always fail to build. A bit annoying when testing features.

**Comment by typemytype** [comment]
I cannot reproduce this

RoboFont version? 
do you use the embedded FDK or a local installed one?

**Comment by rbmntjs** [comment]
Version 1.6, embedded FDK. A restart of the application fixes this error. I wish I understood it better.

**Comment by ryanbugden** [comment]
I’m having this issue today with TTF-flavored WOFF2s.

```
Build WOFF2 (TTF)
'''''''''''''''''
    Failed:
    Traceback (most recent call last):
      File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 566, in run
      File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 460, in _convertPath
      File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 162, in convertToWoff2
      File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/woff2Builder.py", line 5, in WOFF2Builder
      File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/fontTools/ttLib/ttFont.py", line 164, in __init__
      File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/fontTools/ttLib/sfnt.py", line 80, in __init__
    fontTools.ttLib.TTLibError: Not a TrueType or OpenType font (not enough data)
    ```
