### ISSUE TITLE
Variable Fonts

### ISSUE THREAD

**Issue by cjdunn** [typemytype/batchRoboFontExtension#13]
I get this traceback:```

---

Traceback (most recent call last):
  File "/Users/cjdunn/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchTools.py", line 123, in runTask_
  File "/Users/cjdunn/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/variableFontGenerator/**init**.py", line 59, in run
  File "/Users/cjdunn/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchTools.py", line 279, in generateVariationFont
AttributeError: 'BathDesignSpaceDocumentReader' object has no attribute 'warpDict'

---

```
could this be a typo: BathDesignSpaceDocumentReader ? 
```

**Comment by typemytype** [comment]
that is idd a typo... fixed https://github.com/typemytype/batchRoboFontExtension/commit/060b8f25a7871b848559556e90c4ffc9224eec29

but the mutator document should have a `warpDict` attribute...
see https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/ufo/document.py#L386-L387

could you send me the `.designSpace` file?

**Comment by typemytype** [comment]
Im going to close this as we evolved a lot since then :)

Please reopen if this is still an issue
