### ISSUE TITLE
ImportError: No module named ufo

### ISSUE THREAD

**Issue by cjdunn** [typemytype/batchRoboFontExtension#22]
I'm getting a traceback when using the latest Batch 1.9.3 with the latest RF 1.8.3 Beta build 1702022141. Batch doesn't show up in the File menu. I had to go back to Batch 1.7. 

Here's the traceback in the output window when I start RF:
```
Deprecated: use 'buildAdditionContextualMenuItems'.
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "...path/to/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/toolBox.py", line 19, in <module>
  File "...path/to/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/variableFontGenerator/__init__.py", line 5, in <module>
ImportError: No module named ufo
```

**Comment by typemytype** [comment]
I guess you local version of `designSpaceDocument` is outdated... and RF is confused on which one to take

```python
import designSpaceDocument
print designSpaceDocument

from designSpaceDocument.ufo import DesignSpaceProcessor
```

**Comment by cjdunn** [comment]
Ah ok, that makes sense. I uninstalled my local version of designSpaceDocument and that solved the problem. Thank you!
