### ISSUE TITLE
ImportError: No module named reverseContourPen

### ISSUE THREAD

**Issue by jeremymickel** [typemytype/batchRoboFontExtension#27]
Hi Frederik, I'm getting an error when I try to install Batch - it says I'm missing reverseContourPen. I've tried reinstalling FontTools / FontMake and cu2qu. Just wondered if you had any advice how to resolve this error.

Thanks in advance.

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
  File "/Users/jeremymickel/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/toolBox.py", line 19, in <module>
  File "/Users/jeremymickel/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/variableFontGenerator/__init__.py", line 15, in <module>
  File "build/bdist.macosx-10.13-intel/egg/cu2qu/ufo.py", line 33, in <module>
  File "build/bdist.macosx-10.13-intel/egg/cu2qu/pens.py", line 4, in <module>
ImportError: No module named reverseContourPen
```

**Comment by typemytype** [comment]
could you report back the output of this script:
```
import cu2qu
print cu2qu
import cu2qu.ufo
print cu2qu.ufo
```

it should be referring to a path inside `RoboFont.app` 

are you injecting path to `sys.path` inside RoboFont?
do you have anything installed in the `sys_path_override` folder inside <user>/Library/Application Support/RoboFont?

**Comment by jeremymickel** [comment]
Thanks Frederik.

I don't have `sys_path_override` folder. And I'm not knowingly injecting anything into `sys.path` - is there a way to check that?

Here is the traceback for the script:

```
<module 'cu2qu' from '/Library/Python/2.7/site-packages/cu2qu-1.3.0-py2.7.egg/cu2qu/__init__.pyc'>
Traceback (most recent call last):
  File "<untitled>", line 3, in <module>
  File "build/bdist.macosx-10.13-intel/egg/cu2qu/ufo.py", line 33, in <module>
  File "build/bdist.macosx-10.13-intel/egg/cu2qu/pens.py", line 4, in <module>
ImportError: No module named reverseContourPen

```

**Comment by typemytype** [comment]
and what RoboFont version are you using?

its weird: `cu2qu` is embedded in RoboFont, it should find that version first before looking in to the local site packages path...

**Comment by jeremymickel** [comment]
Thanks Frederik.

Version 1.8.3b (built 1702022141)

On Mon, Dec 11, 2017 at 12:26 AM, Frederik Berlaen <notifications@github.com

**Comment by typemytype** [comment]
could you update to the latest version?



gr Frederik
www.typemytype.com

**Comment by jeremymickel** [comment]
Hi Frederick, you mean to RF2? Not for my primary workflow just yet. I have
the latest version of 1.8, right?

**Comment by jeremymickel** [comment]
I installed RF2 and Batch works correctly, no error messages. Still doesn't
work in 1.8 though.

Thanks again.

**Comment by typemytype** [comment]
1.8.4 is the latest retail version

**Comment by jeremymickel** [comment]
Thanks Frederik - updated to 1.8.4 but still get the same error. 

<img width="792" alt="screen shot 2017-12-13 at 2 33 29 pm" src="https://user-images.githubusercontent.com/2964496/33965987-b57be9b8-e012-11e7-8a2c-5186f3c94aad.png">

**Comment by typemytype** [comment]
mmm, still weird it finds the external cu2qu first before the internal one.

could you check inside RoboFont: "RoboFont.app/Resources/lib/Python2.7"
and see if cu2qu is in there
