### ISSUE TITLE
Batch not generating SVGs neither WOFF

### ISSUE THREAD

**Issue by sannorozco** [typemytype/batchRoboFontExtension#6]
Hallo Frederik,

I’m getting this error while trying to generate webfonts:

---

Build WOFF (TTF)
''''''''''''''''
    path: 
    Failed:
    Traceback (most recent call last):
      File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/**init**.py", line 536, in run
      File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/**init**.py", line 418, in _convertPath
      File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 154, in convertToWoff
      File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/woffBuilder.py", line 162, in WOFFBuilder
      File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/woffBuilder.py", line 33, in **init**
    AttributeError: Format

---

I’m using FBs Robofont, and a few weeks back I used it without problem. Do you think this could be affecting?

Thanks!

**Comment by sannorozco** [comment]
Hallo Frederik, I think I found why it doesn’t generate WOFF neither SVG,

I had a UFO without kerning, when generating  with Batch,make all the web fonts, but when importing the kerning with MetricsMachine from fea or AFM, Batch doesn’t generate these files and throws the above error:

Build WOFF (TTF)
''''''''''''''''
path: 
Failed:
Traceback (most recent call last):
File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/init.py", line 536, in run
File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/init.py", line 418, in convertPath
File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init_.py", line 154, in convertToWoff
File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/woffBuilder.py", line 162, in WOFFBuilder
File "/Users/SO/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/woffBuilder.py", line 33, in init
AttributeError: Format

Hope this is a quick fix, thanks!

**Comment by typemytype** [comment]
This issue should be solved in the latest RoboFont 1.7
There was an issue in fontTools related to the removed 'format' attribute

**Comment by typemytype** [comment]
Reopen if this is still an issue, I guess this is solved allong the way
Thanks
