### ISSUE TITLE
problem, while exporting VF with DesignSpace format 5

### ISSUE THREAD

**Issue by RafalBuchner** [typemytype/batchRoboFontExtension#63]
Hey, I'm having issue with designspace's Discrete Axes

```******************************
Traceback (most recent call last):
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchTools.py", line 109, in runTask_
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/variableFontGenerator/__init__.py", line 87, in run
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/variableFontGenerator/__init__.py", line 299, in generateVariationFont
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/variableFontGenerator/__init__.py", line 457, in makeMasterGlyphsCompatible
  File "/Users/rafalbuchner/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/variableFontGenerator/__init__.py", line 447, in makeMasterGlyphsCompatible
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ufoProcessor/__init__.py", line 464, in getGlyphMutator
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ufoProcessor/__init__.py", line 323, in getSerializedAxes
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ufoProcessor/__init__.py", line 323, in <listcomp>
AttributeError: 'DiscreteAxisDescriptor' object has no attribute 'serialize'

******************************
```

here is design space example:

```
<?xml version='1.0' encoding='utf-8'?>
<designspace format="5">
    <axes>
        <axis default="0" maximum="1000" minimum="0" name="Weight" tag="wght"/>
        <axis tag="ital" name="Italic" values="0 1" default="1"/>
    </axes>
    <sources>
        <source filename="Font-Thin Italic 17.ufo">
            <location>
                <dimension name="Weight" xvalue="0"/>
                <dimension name="Italic" xvalue="1"/>
            </location>
        </source>
        <source filename="Font-RegularItalic 02.ufo">
            <location>
                <dimension name="Weight" xvalue="430"/>
                <dimension name="Italic" xvalue="1"/>
            </location>
        </source>
        <source filename="Font-Bold Italic 18.ufo">
            <location>
                <dimension name="Weight" xvalue="1000"/>
                <dimension name="Italic" xvalue="1"/>
            </location>
        </source>
    </sources>
</designspace>
```

**Comment by roberto-arista** [comment]
Hey Rafal, the version of Batch on the main branch does not support DS5.
There's a new version on development on branch "ds5".
