### ISSUE TITLE
[ds5] Can't generate Variable fonts. Half of the instances in statics aren't getting generated as well.

### ISSUE THREAD

**Issue by ryanbugden** [typemytype/batchRoboFontExtension#66]
Traceback from two separate tries
```
Traceback (most recent call last):
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/vanilla/dialogs.py", line 134, in completionHandler_
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/ezui/controllers.py", line 475, in _internalGetFolderCallbackReroute
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batch.py", line 232, in result
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/webFontsGenerator/__init__.py", line 95, in build
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/batchTools.py", line 246, in generatePaths
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/batchTools.py", line 150, in __call__
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/webFontsGenerator/__init__.py", line 51, in wrapper
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/webFontsGenerator/autohint.py", line 89, in TTFAutohint
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/fontTools/ttLib/ttFont.py", line 146, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Ryan/Documents/Git/private/Meek/v02/_test/Web/ttf/temp_MeekDisplay-Mediumv39.ttf'
/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/ufoProcessor/ufoOperator.py:733: DeprecationWarning: The doRules argument in DesignSpaceProcessor.makeInstance() is deprecated
Traceback (most recent call last):
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/vanilla/dialogs.py", line 134, in completionHandler_
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/ezui/controllers.py", line 475, in _internalGetFolderCallbackReroute
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batch.py", line 232, in result
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/webFontsGenerator/__init__.py", line 95, in build
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/batchTools.py", line 246, in generatePaths
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/batchTools.py", line 150, in __call__
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/webFontsGenerator/__init__.py", line 51, in wrapper
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/webFontsGenerator/autohint.py", line 89, in TTFAutohint
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/fontTools/ttLib/ttFont.py", line 146, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Ryan/Documents/test/Web/otf/temp_ClientVariable-ExtraBold.otf'
```

**Comment by typemytype** [comment]
I would need more info... can you share the designspace? or make a simple one that produces this

thanks!

**Comment by ryanbugden** [comment]
I think this has been fixed. Closing for now.
