### ISSUE TITLE
AssertionError: PUSHW value out of range

### ISSUE THREAD

**Issue by rbmntjs** [typemytype/batchRoboFontExtension#9]
When trying to export web font files, I run into a strange issue that then breaks the current ‘run’: the error doesn’t return, but every following export fails with the message `TTLibError: Not a TrueType or OpenType font (not enough data)`; the `PUSHW` error returns after I restart RoboFont.

For what it’s worth, I can’t get the extension to export TTFs regardless of these errors. Perhaps warrants its own issue, but I can’t find a traceback anywhere, and no report file. The normal Generate function works fine – TTFs roll out, and `ttf2woff` and `ttf2eot` convert without a hitch.

```
Build WOFF (TTF)
''''''''''''''''
    path: […]/Dover_Serif_Display-Italic.woff
    Source is a UFO file. Generate TTF.
        Failed:
        Traceback (most recent call last):
          File "/Users/rob/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 553, in run
          File "/Users/rob/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 433, in _convertPath
          File "/Users/rob/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 326, in _getTempTTF
          File "/Users/rob/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/webFormats/__init__.py", line 132, in generateTTF
          File "lib/fontObjects/robofabWrapper.pyc", line 3901, in generate
          File "lib/fontObjects/doodleFont.pyc", line 882, in generate
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/compiler.py", line 127, in generateFont
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/baseCompiler.py", line 309, in compile
          File "ufo2fdk/makeotfParts.pyc", line 66, in compile
          File "ufo2fdk/makeotfParts.pyc", line 81, in setupFile_outlineSource
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/ttfCompiler.py", line 261, in compile
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 216, in save
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 648, in _writeTable
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 659, in getTableData
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_f_p_g_m.py", line 14, in compile
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 222, in getBytecode
          File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 396, in _assemble
        AssertionError: PUSHW value out of range 262144
```

**Comment by rbmntjs** [comment]
Well, as I post this, I am getting the PUSHW error on only one file: the italics. Now it looks like a font issue, not a Batch issue. Still curious what this error is, as I can’t find a reference to it anywhere else.

```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/dialogs.py", line 110, in savePanelDidEnd_returnCode_contextInfo_
    self._resultCallback(self._result)
  File "lib/doodleFontWindow.pyc", line 413, in _compileFont
  File "lib/fontObjects/doodleFont.pyc", line 882, in generate
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/compiler.py", line 127, in generateFont
    reports = compiler.compile(outputFont, options)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/baseCompiler.py", line 309, in compile
    partsCompiler.compile()
  File "ufo2fdk/makeotfParts.pyc", line 66, in compile
  File "ufo2fdk/makeotfParts.pyc", line 81, in setupFile_outlineSource
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/ttfCompiler.py", line 261, in compile
    self.otf.save(self.path)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_f_p_g_m.py", line 14, in compile
    return self.program.getBytecode()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 222, in getBytecode
    self._assemble()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 396, in _assemble
    assert -32768 <= value < 32768, "PUSHW value out of range %d" % value
AssertionError: PUSHW value out of range 262144
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 169, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/dialogs.py", line 110, in savePanelDidEnd_returnCode_contextInfo_
    self._resultCallback(self._result)
  File "lib/doodleFontWindow.pyc", line 413, in _compileFont
  File "lib/fontObjects/doodleFont.pyc", line 882, in generate
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/compiler.py", line 127, in generateFont
    reports = compiler.compile(outputFont, options)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/baseCompiler.py", line 309, in compile
    partsCompiler.compile()
  File "ufo2fdk/makeotfParts.pyc", line 66, in compile
  File "ufo2fdk/makeotfParts.pyc", line 81, in setupFile_outlineSource
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/ttfCompiler.py", line 261, in compile
    self.otf.save(self.path)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_f_p_g_m.py", line 14, in compile
    return self.program.getBytecode()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 222, in getBytecode
    self._assemble()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 396, in _assemble
    assert -32768 <= value < 32768, "PUSHW value out of range %d" % value
AssertionError: PUSHW value out of range 262144
```

**Comment by rbmntjs** [comment]
Well, it took some digging. Apparently, I had at some point tried RoboHint, and now it left me with some junk in `lib.plist`. After removing all reference to it, I managed to build.
